language: node_js
node_js:
  - "8.9.4"
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database lenscape_test;' -U postgres
before_install:
  - docker run -d -p 127.0.0.1:9000:9000 h2non/imaginary
cache:
  directories:
    - "node_modules"