language: node_js
node_js:
- 8.9.4
services:
- postgresql
- docker
before_script:
- psql -c 'create database lenscape_test;' -U postgres
before_install:
- docker run -d -p 127.0.0.1:9000:9000 h2non/imaginary
cache:
  directories:
  - node_modules
deploy:
  provider: gcs
  secret_access_key:
    secure: V1Sn+whb3Ajo9SE2auqBhcNtJR4wSwk7w8VUDgZ7s9SFG+OD7o2s5tVHP7sewevlcKbUYjrhIkfvEjwecWgTgjKKDksLkWonhQShbs+IzFjP4XVpMoM7oiqfsjA20hWER56cQq+tv+BG518TnkYhx2GwhonepVcasUtMGZrJWGesriABkyov25wWJB1S81XwCT8DeL8auSRFkGWMBisGVmWfa3awbUyj2RzKmp7oN33sVkgfBiy6Ii9RlfXrt8H1yG4dq02tO3Az4dBlAUWHxx6rmNyBXJlW49Ax6aPZMB4SmpA7efMifp9Gm2sE3cb1vWsmT/sEBZX7B62GC4OazK0YC3F+qC2VcqkRVBd3mZ4w5mx7YkBNwkCce77IcQ+tbQyM14odf9QBF9QXjfzf80sNNdeNZ1z/UKPtkNNLwM9FlZMOh8RjXO00M/yvgbFUiMcI+XSFspkOZLKYwp9hosxgZiYfHEZGJcavIjDux28NWEgkukv097eH4WNS2IE2pgWn/py0zMYr0r+86JLb/vktXSTjwDuAdwhsrwAoeuMxtJrb/yxwUrga7OcdC8iuKve7SDiH1yKVdGCh7xIkJpEMimszkCRCul+IOJNH7lnICrl2N23+KMbrZiof0eqYSAOeQ0uWwSVv5hQfc5h23nhu6X9i9oi/D6pQjaZFSws=
