apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lenscape-monolith
  labels:
    app: lenscape-monolith
spec:
  template:
    metadata:
      labels:
        app: lenscape-monolith
    spec:
      containers:
        - name: lenscape-monolith-server
          image: gcr.io/lenscapeapp/github-lenscapeapp-monolith-server:8a99d008850f7b9323b0e694597fc7e5ec3b2298
          imagePullPolicy: Always 
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: POSTGRES_DB_HOST
              value: localhost 
            # [START] cloudsql secrets
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-maps-api-key
                  key: API_KEY
            # [END] cloudsql secrets
        # [START] cloudsql proxy
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=lenscapeapp:asia-east1:lenscape-db=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END] cloudsql proxy
      # [START] volumes
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END] volumes 
